-- ============================================
-- PharmaSmart - Script 01
-- Creación de Tablespace y Usuario
-- Ejecutar como SYSDBA
-- ============================================

SET SERVEROUTPUT ON;
SET ECHO ON;
SET LINESIZE 200;

-- Eliminar si existe (para reinstalación limpia)
BEGIN
    EXECUTE IMMEDIATE 'DROP USER PHARMA_USER CASCADE';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLESPACE TS_PHARMASMART INCLUDING CONTENTS AND DATAFILES';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLESPACE TS_PHARMASMART_TEMP INCLUDING CONTENTS AND DATAFILES';
EXCEPTION
    WHEN OTHERS THEN NULL;
END;
/

-- Crear Tablespace de datos
CREATE TABLESPACE TS_PHARMASMART
    DATAFILE 'ts_pharmasmart01.dbf' 
    SIZE 100M 
    AUTOEXTEND ON 
    NEXT 50M 
    MAXSIZE 2G
    EXTENT MANAGEMENT LOCAL 
    SEGMENT SPACE MANAGEMENT AUTO;

-- Crear Tablespace temporal
CREATE TEMPORARY TABLESPACE TS_PHARMASMART_TEMP
    TEMPFILE 'ts_pharmasmart_temp01.dbf'
    SIZE 50M
    AUTOEXTEND ON
    NEXT 25M
    MAXSIZE 500M;

-- Crear usuario
CREATE USER PHARMA_USER
    IDENTIFIED BY Pharma123
    DEFAULT TABLESPACE TS_PHARMASMART
    TEMPORARY TABLESPACE TS_PHARMASMART_TEMP
    QUOTA UNLIMITED ON TS_PHARMASMART;

-- Otorgar permisos
GRANT CREATE SESSION TO PHARMA_USER;
GRANT CREATE TABLE TO PHARMA_USER;
GRANT CREATE VIEW TO PHARMA_USER;
GRANT CREATE SEQUENCE TO PHARMA_USER;
GRANT CREATE PROCEDURE TO PHARMA_USER;
GRANT CREATE TRIGGER TO PHARMA_USER;
GRANT CREATE TYPE TO PHARMA_USER;
GRANT CREATE SYNONYM TO PHARMA_USER;
GRANT DEBUG CONNECT SESSION TO PHARMA_USER;
GRANT DEBUG ANY PROCEDURE TO PHARMA_USER;

COMMIT;

-- Verificación
SELECT 'Tablespace creado: TS_PHARMASMART' AS MENSAJE FROM DUAL;
SELECT 'Tablespace temporal creado: TS_PHARMASMART_TEMP' AS MENSAJE FROM DUAL;
SELECT 'Usuario creado: PHARMA_USER / Pharma123' AS MENSAJE FROM DUAL;
SELECT 'Instalación del Script 01 completada.' AS MENSAJE FROM DUAL;

EXIT;