-- ============================================
-- PharmaSmart - Script 03
-- Creación de Índices
-- Ejecutar como PHARMA_USER
-- ============================================

SET SERVEROUTPUT ON;
SET ECHO ON;

CREATE INDEX IDX_LOTE_PRODUCTO ON LOTE(PRODUCTO_ID);
CREATE INDEX IDX_LOTE_VENCIMIENTO ON LOTE(FECHA_VENCIMIENTO);
CREATE INDEX IDX_LOTE_ESTADO ON LOTE(ESTADO);
CREATE INDEX IDX_DETALLE_VENTA_V ON DETALLE_VENTA(VENTA_ID);
CREATE INDEX IDX_DETALLE_VENTA_L ON DETALLE_VENTA(LOTE_ID);
CREATE INDEX IDX_VENTA_USUARIO ON VENTA(USUARIO_ID);
CREATE INDEX IDX_VENTA_FECHA ON VENTA(FECHA_VENTA);
CREATE INDEX IDX_HP_CLAVE ON HISTORIAL_PARAMETRO(CLAVE_PARAMETRO);
CREATE INDEX IDX_HP_FECHA ON HISTORIAL_PARAMETRO(FECHA_CAMBIO);
CREATE INDEX IDX_HDP_PRODUCTO ON HISTORIAL_DESCUENTO_PRODUCTO(PRODUCTO_ID);
CREATE INDEX IDX_AI_PRODUCTO ON ALERTA_INFLACION(PRODUCTO_ID);
CREATE INDEX IDX_AF_CLIENTE ON ALERTA_FIDELIZACION(CLIENTE_ID);
CREATE INDEX IDX_LOTE_FEFO ON LOTE(PRODUCTO_ID, FECHA_VENCIMIENTO, CANTIDAD_ACTUAL, ESTADO);
CREATE INDEX IDX_VENTA_ANULADA ON VENTA(ANULADA, FECHA_VENTA);

COMMIT;

SELECT 'Indices creados: 14' AS MENSAJE FROM DUAL;
SELECT INDEX_NAME, TABLE_NAME FROM USER_INDEXES WHERE INDEX_NAME LIKE 'IDX_%' ORDER BY INDEX_NAME;

EXIT;