-- ============================================
-- PharmaSmart - Script 04
-- Creación de Secuencias
-- Ejecutar como PHARMA_USER
-- ============================================

SET SERVEROUTPUT ON;
SET ECHO ON;

PROMPT Creando secuencias...

CREATE SEQUENCE SEQ_NUMERO_FACTURA START WITH 1000 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HISTORIAL_PARAMETRO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_HISTORIAL_DESCUENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ALERTA_INFLACION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_ALERTA_FIDELIZACION START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

COMMIT;

PROMPT Secuencias creadas: 5
EXIT;