-- ============================================
-- PharmaSmart - Script 07 (CORREGIDO)
-- Package PKG_PHARMASMART_VENTAS
-- Ejecutar como PHARMA_USER
-- ============================================

SET SERVEROUTPUT ON;
SET ECHO ON;

CREATE OR REPLACE PACKAGE PKG_PHARMASMART_VENTAS AS
    
    PROCEDURE CREAR_VENTA(
        p_id_usuario NUMBER, p_id_cliente NUMBER, p_subtotal NUMBER,
        p_descuento_total NUMBER, p_total NUMBER,
        p_id_venta OUT NUMBER, p_numero_factura OUT VARCHAR2
    );
    
    PROCEDURE INSERTAR_DETALLE(
        p_id_venta NUMBER, p_id_producto NUMBER, p_id_lote NUMBER,
        p_cantidad NUMBER, p_precio_aplicado NUMBER, p_descuento_unitario NUMBER
    );
    
    PROCEDURE ANULAR_VENTA(p_id_venta NUMBER, p_id_usuario NUMBER);
    
    FUNCTION OBTENER_VENTA(p_id_venta NUMBER) RETURN T_VENTA_INFO;
    
    PROCEDURE OBTENER_VENTA_POR_FACTURA(p_numero_factura VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_VENTAS_USUARIO(p_id_usuario NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_VENTAS_FECHAS(p_desde DATE, p_hasta DATE, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_DETALLES_VENTA(p_id_venta NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_DETALLES_POR_LOTE(p_id_lote NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_AJUSTES_POR_LOTE(p_id_lote NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_AJUSTES_POR_RESPONSABLE(p_id_usuario NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_AJUSTES_POR_FECHAS(p_desde DATE, p_hasta DATE, p_cursor OUT SYS_REFCURSOR);
    
END PKG_PHARMASMART_VENTAS;
/

CREATE OR REPLACE PACKAGE BODY PKG_PHARMASMART_VENTAS AS

    PROCEDURE CREAR_VENTA(
        p_id_usuario NUMBER, p_id_cliente NUMBER, p_subtotal NUMBER,
        p_descuento_total NUMBER, p_total NUMBER,
        p_id_venta OUT NUMBER, p_numero_factura OUT VARCHAR2
    ) IS
        v_numero VARCHAR2(20);
    BEGIN
        v_numero := 'FAC-' || TO_CHAR(SYSDATE, 'YYYYMMDD') || '-' || LPAD(SEQ_NUMERO_FACTURA.NEXTVAL, 5, '0');
        INSERT INTO VENTAS (NUMERO_FACTURA, FECHA_VENTA, ID_USUARIO, ID_CLIENTE, SUBTOTAL, DESCUENTO_TOTAL, TOTAL)
        VALUES (v_numero, SYSDATE, p_id_usuario, p_id_cliente, p_subtotal, p_descuento_total, p_total)
        RETURNING ID_VENTA INTO p_id_venta;
        p_numero_factura := v_numero;
        COMMIT;
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
    END;

    PROCEDURE INSERTAR_DETALLE(
        p_id_venta NUMBER, p_id_producto NUMBER, p_id_lote NUMBER,
        p_cantidad NUMBER, p_precio_aplicado NUMBER, p_descuento_unitario NUMBER
    ) IS
        v_cantidad_actual NUMBER;
    BEGIN
        SELECT CANTIDAD_ACTUAL INTO v_cantidad_actual FROM LOTES WHERE ID_LOTE = p_id_lote FOR UPDATE;
        IF v_cantidad_actual < p_cantidad THEN
            RAISE_APPLICATION_ERROR(-20001, 'Stock insuficiente. Disponible: ' || v_cantidad_actual);
        END IF;
        INSERT INTO DETALLES_VENTAS (ID_VENTA, ID_PRODUCTO, ID_LOTE, CANTIDAD, PRECIO_APLICADO, DESCUENTO_UNITARIO)
        VALUES (p_id_venta, p_id_producto, p_id_lote, p_cantidad, p_precio_aplicado, p_descuento_unitario);
        UPDATE LOTES SET CANTIDAD_ACTUAL = CANTIDAD_ACTUAL - p_cantidad,
            ESTADO = CASE WHEN (CANTIDAD_ACTUAL - p_cantidad) = 0 THEN 'B' ELSE 'A' END
        WHERE ID_LOTE = p_id_lote;
        COMMIT;
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
    END;

    PROCEDURE ANULAR_VENTA(p_id_venta NUMBER, p_id_usuario NUMBER) IS
        CURSOR c_det IS SELECT ID_LOTE, CANTIDAD FROM DETALLES_VENTAS WHERE ID_VENTA = p_id_venta;
    BEGIN
        FOR det IN c_det LOOP
            UPDATE LOTES SET CANTIDAD_ACTUAL = CANTIDAD_ACTUAL + det.CANTIDAD,
                ESTADO = CASE WHEN CANTIDAD_ACTUAL + det.CANTIDAD > 0 THEN 'A' ELSE ESTADO END
            WHERE ID_LOTE = det.ID_LOTE;
        END LOOP;
        UPDATE VENTAS SET ESTADO = 'N', FECHA_ANULACION = SYSDATE, ANULADA_POR = p_id_usuario WHERE ID_VENTA = p_id_venta;
        COMMIT;
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
    END;

    FUNCTION OBTENER_VENTA(p_id_venta NUMBER) RETURN T_VENTA_INFO IS
        v_result T_VENTA_INFO;
    BEGIN
        SELECT T_VENTA_INFO(ID_VENTA, NUMERO_FACTURA, FECHA_VENTA, TOTAL, ESTADO)
        INTO v_result FROM VENTAS WHERE ID_VENTA = p_id_venta;
        RETURN v_result;
    EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL;
    END;

    PROCEDURE OBTENER_VENTA_POR_FACTURA(p_numero_factura VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM VENTAS WHERE NUMERO_FACTURA = p_numero_factura; END;

    PROCEDURE OBTENER_VENTAS_USUARIO(p_id_usuario NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM VENTAS WHERE ID_USUARIO = p_id_usuario AND ESTADO = 'A' ORDER BY FECHA_VENTA DESC; END;

    PROCEDURE OBTENER_VENTAS_FECHAS(p_desde DATE, p_hasta DATE, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM VENTAS WHERE FECHA_VENTA BETWEEN p_desde AND p_hasta AND ESTADO = 'A' ORDER BY FECHA_VENTA DESC; END;

    PROCEDURE OBTENER_DETALLES_VENTA(p_id_venta NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT dv.*, p.NOMBRE, l.CODIGO_LOTE
        FROM DETALLES_VENTAS dv JOIN PRODUCTOS p ON dv.ID_PRODUCTO = p.ID_PRODUCTO JOIN LOTES l ON dv.ID_LOTE = l.ID_LOTE
        WHERE dv.ID_VENTA = p_id_venta; END;

    PROCEDURE OBTENER_DETALLES_POR_LOTE(p_id_lote NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM DETALLES_VENTAS WHERE ID_LOTE = p_id_lote; END;

    PROCEDURE OBTENER_AJUSTES_POR_LOTE(p_id_lote NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM AJUSTES_INVENTARIO WHERE ID_LOTE = p_id_lote ORDER BY FECHA_AJUSTE DESC; END;

    PROCEDURE OBTENER_AJUSTES_POR_RESPONSABLE(p_id_usuario NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM AJUSTES_INVENTARIO WHERE ID_RESPONSABLE = p_id_usuario ORDER BY FECHA_AJUSTE DESC; END;

    PROCEDURE OBTENER_AJUSTES_POR_FECHAS(p_desde DATE, p_hasta DATE, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM AJUSTES_INVENTARIO WHERE FECHA_AJUSTE BETWEEN p_desde AND p_hasta ORDER BY FECHA_AJUSTE DESC; END;

END PKG_PHARMASMART_VENTAS;
/

COMMIT;
PROMPT Package VENTAS creado.
EXIT;