-- ============================================
-- PharmaSmart - Script 08
-- Package PKG_PHARMASMART_CONFIG 
-- Ejecutar como PHARMA_USER
-- ============================================

SET SERVEROUTPUT ON;
SET ECHO ON;

CREATE OR REPLACE PACKAGE PKG_PHARMASMART_CONFIG AS
    
    FUNCTION OBTENER_PARAMETRO(p_clave VARCHAR2) RETURN VARCHAR2;
    
    PROCEDURE ACTUALIZAR_DESCUENTO_GENERAL(
        p_nuevo_valor VARCHAR2, p_usuario_id NUMBER, p_motivo VARCHAR2, p_ip VARCHAR2 DEFAULT NULL
    );
    
    PROCEDURE ACTUALIZAR_DESCUENTO_PRODUCTO(
        p_producto_id NUMBER, p_descuento NUMBER, p_usuario_id NUMBER,
        p_motivo VARCHAR2, p_ip VARCHAR2 DEFAULT NULL
    );
    
    PROCEDURE REGISTRAR_AJUSTE(
        p_lote_id NUMBER, p_tipo VARCHAR2, p_cantidad NUMBER,
        p_motivo VARCHAR2, p_responsable_id NUMBER
    );
    
    PROCEDURE OBTENER_HISTORIAL_PARAMETROS(p_clave VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_HISTORIAL_POR_USUARIO(p_usuario_id NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_HISTORIAL_POR_FECHAS(p_desde DATE, p_hasta DATE, p_cursor OUT SYS_REFCURSOR);
    
    PROCEDURE OBTENER_HISTORIAL_DESCUENTOS(p_producto_id NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_TODO_HISTORIAL_DESCUENTO(p_cursor OUT SYS_REFCURSOR);
    
    -- PRODUCTO
    PROCEDURE OBTENER_PRODUCTO_POR_CODIGO(p_codigo VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_PRODUCTO_POR_ID(p_id NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_PRODUCTO_POR_NOMBRE(p_nombre VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_TODOS_PRODUCTOS(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE INSERTAR_PRODUCTO(p_codigo VARCHAR2, p_nombre VARCHAR2, p_descripcion VARCHAR2,
        p_es_controlado NUMBER, p_stock_minimo NUMBER, p_descuento NUMBER);
    PROCEDURE ACTUALIZAR_PRODUCTO(p_id NUMBER, p_nombre VARCHAR2, p_descripcion VARCHAR2,
        p_es_controlado NUMBER, p_stock_minimo NUMBER, p_descuento NUMBER);
    PROCEDURE ELIMINAR_PRODUCTO(p_id NUMBER);
    
    -- USUARIO
    PROCEDURE OBTENER_USUARIO_POR_CREDENCIALES(p_nombre VARCHAR2, p_hash VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_USUARIO_POR_ID(p_id NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_USUARIO_POR_DOCUMENTO(p_doc VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_TODOS_USUARIOS(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE INSERTAR_USUARIO(p_user VARCHAR2, p_hash VARCHAR2, p_nombre VARCHAR2, p_rol NUMBER, p_doc VARCHAR2);
    PROCEDURE ACTUALIZAR_USUARIO(p_id NUMBER, p_nombre VARCHAR2, p_rol NUMBER, p_activo NUMBER);
    
    -- CLIENTE
    PROCEDURE OBTENER_CLIENTE_POR_DOCUMENTO(p_doc VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_CLIENTE_POR_ID(p_id NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_CLIENTE_POR_CHAT_ID(p_chat VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_CLIENTES_FIDELIZACION(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE INSERTAR_CLIENTE(p_doc VARCHAR2, p_nombre VARCHAR2, p_tel VARCHAR2,
        p_correo VARCHAR2, p_chat VARCHAR2, p_med VARCHAR2);
    PROCEDURE ACTUALIZAR_CLIENTE(p_id NUMBER, p_nombre VARCHAR2, p_tel VARCHAR2,
        p_correo VARCHAR2, p_chat VARCHAR2, p_med VARCHAR2);
    
    -- PARAMETRO
    PROCEDURE OBTENER_TODOS_PARAMETROS(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE INSERTAR_PARAMETRO(p_clave VARCHAR2, p_valor VARCHAR2, p_desc VARCHAR2);
    
END PKG_PHARMASMART_CONFIG;
/

CREATE OR REPLACE PACKAGE BODY PKG_PHARMASMART_CONFIG AS

    FUNCTION OBTENER_PARAMETRO(p_clave VARCHAR2) RETURN VARCHAR2 IS
        v_valor VARCHAR2(50);
    BEGIN
        SELECT VALOR INTO v_valor FROM PARAMETRO_SISTEMA WHERE CLAVE = p_clave AND ACTIVO = 1;
        RETURN v_valor;
    EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL;
    END;

    PROCEDURE ACTUALIZAR_DESCUENTO_GENERAL(
        p_nuevo_valor VARCHAR2, p_usuario_id NUMBER, p_motivo VARCHAR2, p_ip VARCHAR2 DEFAULT NULL
    ) IS
        v_rol NUMBER; v_anterior VARCHAR2(50);
    BEGIN
        SELECT ROL INTO v_rol FROM USUARIO WHERE ID = p_usuario_id;
        IF v_rol != 1 THEN RAISE_APPLICATION_ERROR(-20004, 'Solo admin.'); END IF;
        SELECT VALOR INTO v_anterior FROM PARAMETRO_SISTEMA WHERE CLAVE = 'PORCENTAJE_DESCUENTO_VENCIMIENTO';
        UPDATE PARAMETRO_SISTEMA SET VALOR = p_nuevo_valor WHERE CLAVE = 'PORCENTAJE_DESCUENTO_VENCIMIENTO';
        INSERT INTO HISTORIAL_PARAMETRO (CLAVE_PARAMETRO, VALOR_ANTERIOR, VALOR_NUEVO, MOTIVO, MODIFICADO_POR_ID, DIRECCION_IP)
        VALUES ('PORCENTAJE_DESCUENTO_VENCIMIENTO', v_anterior, p_nuevo_valor, p_motivo, p_usuario_id, p_ip);
        COMMIT;
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
    END;

    PROCEDURE ACTUALIZAR_DESCUENTO_PRODUCTO(
        p_producto_id NUMBER, p_descuento NUMBER, p_usuario_id NUMBER, p_motivo VARCHAR2, p_ip VARCHAR2 DEFAULT NULL
    ) IS
        v_rol NUMBER; v_prod PRODUCTO%ROWTYPE; v_accion VARCHAR2(20);
    BEGIN
        SELECT ROL INTO v_rol FROM USUARIO WHERE ID = p_usuario_id;
        IF v_rol != 1 THEN RAISE_APPLICATION_ERROR(-20004, 'Solo admin.'); END IF;
        SELECT * INTO v_prod FROM PRODUCTO WHERE ID = p_producto_id;
        IF v_prod.DESCUENTO_PROXIMIDAD_VENCIMIENTO IS NULL AND p_descuento IS NOT NULL THEN v_accion := 'CREAR';
        ELSIF v_prod.DESCUENTO_PROXIMIDAD_VENCIMIENTO IS NOT NULL AND p_descuento IS NULL THEN v_accion := 'ELIMINAR';
        ELSE v_accion := 'MODIFICAR'; END IF;
        INSERT INTO HISTORIAL_DESCUENTO_PRODUCTO (PRODUCTO_ID, CODIGO_PRODUCTO, NOMBRE_PRODUCTO,
            DESCUENTO_ANTERIOR, DESCUENTO_NUEVO, ACCION, MOTIVO, MODIFICADO_POR_ID, DIRECCION_IP)
        VALUES (p_producto_id, v_prod.CODIGO, v_prod.NOMBRE, v_prod.DESCUENTO_PROXIMIDAD_VENCIMIENTO,
                p_descuento, v_accion, p_motivo, p_usuario_id, p_ip);
        UPDATE PRODUCTO SET DESCUENTO_PROXIMIDAD_VENCIMIENTO = p_descuento WHERE ID = p_producto_id;
        COMMIT;
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
    END;

    PROCEDURE REGISTRAR_AJUSTE(
        p_lote_id NUMBER, p_tipo VARCHAR2, p_cantidad NUMBER, p_motivo VARCHAR2, p_responsable_id NUMBER
    ) IS
        v_estado NUMBER; v_cant NUMBER;
    BEGIN
        INSERT INTO AJUSTE_INVENTARIO (LOTE_ID, TIPO, CANTIDAD, MOTIVO, RESPONSABLE_ID)
        VALUES (p_lote_id, p_tipo, p_cantidad, p_motivo, p_responsable_id);
        SELECT CANTIDAD_ACTUAL + p_cantidad INTO v_cant FROM LOTE WHERE ID = p_lote_id;
        IF v_cant <= 0 THEN v_estado := 3;
        ELSIF p_tipo = 'Vencido' THEN v_estado := 3;
        ELSIF p_tipo = 'RetiroLegal' THEN v_estado := 4;
        ELSE SELECT ESTADO INTO v_estado FROM LOTE WHERE ID = p_lote_id; END IF;
        UPDATE LOTE SET CANTIDAD_ACTUAL = v_cant, ESTADO = v_estado WHERE ID = p_lote_id;
        COMMIT;
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE;
    END;

    PROCEDURE OBTENER_HISTORIAL_PARAMETROS(p_clave VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, CLAVE_PARAMETRO, VALOR_ANTERIOR, VALOR_NUEVO, MOTIVO,
        FECHA_CAMBIO, MODIFICADO_POR_ID, DIRECCION_IP FROM HISTORIAL_PARAMETRO
        WHERE CLAVE_PARAMETRO = p_clave ORDER BY FECHA_CAMBIO DESC; END;

    PROCEDURE OBTENER_HISTORIAL_POR_USUARIO(p_usuario_id NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, CLAVE_PARAMETRO, VALOR_ANTERIOR, VALOR_NUEVO, MOTIVO,
        FECHA_CAMBIO, MODIFICADO_POR_ID, DIRECCION_IP FROM HISTORIAL_PARAMETRO
        WHERE MODIFICADO_POR_ID = p_usuario_id ORDER BY FECHA_CAMBIO DESC; END;

    PROCEDURE OBTENER_HISTORIAL_POR_FECHAS(p_desde DATE, p_hasta DATE, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, CLAVE_PARAMETRO, VALOR_ANTERIOR, VALOR_NUEVO, MOTIVO,
        FECHA_CAMBIO, MODIFICADO_POR_ID, DIRECCION_IP FROM HISTORIAL_PARAMETRO
        WHERE FECHA_CAMBIO BETWEEN p_desde AND p_hasta ORDER BY FECHA_CAMBIO DESC; END;

    PROCEDURE OBTENER_HISTORIAL_DESCUENTOS(p_producto_id NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, PRODUCTO_ID, CODIGO_PRODUCTO, NOMBRE_PRODUCTO,
        DESCUENTO_ANTERIOR, DESCUENTO_NUEVO, ACCION, MOTIVO, FECHA_CAMBIO, MODIFICADO_POR_ID
        FROM HISTORIAL_DESCUENTO_PRODUCTO WHERE PRODUCTO_ID = p_producto_id ORDER BY FECHA_CAMBIO DESC; END;

    PROCEDURE OBTENER_TODO_HISTORIAL_DESCUENTO(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, PRODUCTO_ID, CODIGO_PRODUCTO, NOMBRE_PRODUCTO,
        DESCUENTO_ANTERIOR, DESCUENTO_NUEVO, ACCION, MOTIVO, FECHA_CAMBIO, MODIFICADO_POR_ID
        FROM HISTORIAL_DESCUENTO_PRODUCTO ORDER BY FECHA_CAMBIO DESC; END;

    -- PRODUCTO
    PROCEDURE OBTENER_PRODUCTO_POR_CODIGO(p_codigo VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO,
        DESCUENTO_PROXIMIDAD_VENCIMIENTO, ACTIVO, FECHA_CREACION FROM PRODUCTO WHERE CODIGO = p_codigo AND ACTIVO = 1; END;

    PROCEDURE OBTENER_PRODUCTO_POR_ID(p_id NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO,
        DESCUENTO_PROXIMIDAD_VENCIMIENTO, ACTIVO, FECHA_CREACION FROM PRODUCTO WHERE ID = p_id; END;

    PROCEDURE OBTENER_PRODUCTO_POR_NOMBRE(p_nombre VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO,
        DESCUENTO_PROXIMIDAD_VENCIMIENTO, ACTIVO, FECHA_CREACION FROM PRODUCTO WHERE UPPER(NOMBRE) = UPPER(p_nombre) AND ACTIVO = 1; END;

    PROCEDURE OBTENER_TODOS_PRODUCTOS(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO,
        DESCUENTO_PROXIMIDAD_VENCIMIENTO, ACTIVO, FECHA_CREACION FROM PRODUCTO WHERE ACTIVO = 1 ORDER BY NOMBRE; END;

    PROCEDURE INSERTAR_PRODUCTO(p_codigo VARCHAR2, p_nombre VARCHAR2, p_descripcion VARCHAR2,
        p_es_controlado NUMBER, p_stock_minimo NUMBER, p_descuento NUMBER) IS
    BEGIN INSERT INTO PRODUCTO (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO, DESCUENTO_PROXIMIDAD_VENCIMIENTO)
        VALUES (p_codigo, p_nombre, p_descripcion, p_es_controlado, p_stock_minimo, p_descuento); COMMIT; END;

    PROCEDURE ACTUALIZAR_PRODUCTO(p_id NUMBER, p_nombre VARCHAR2, p_descripcion VARCHAR2,
        p_es_controlado NUMBER, p_stock_minimo NUMBER, p_descuento NUMBER) IS
    BEGIN UPDATE PRODUCTO SET NOMBRE = p_nombre, DESCRIPCION = p_descripcion, ES_CONTROLADO = p_es_controlado,
        STOCK_MINIMO = p_stock_minimo, DESCUENTO_PROXIMIDAD_VENCIMIENTO = p_descuento WHERE ID = p_id; COMMIT; END;

    PROCEDURE ELIMINAR_PRODUCTO(p_id NUMBER) IS
    BEGIN UPDATE PRODUCTO SET ACTIVO = 0 WHERE ID = p_id; COMMIT; END;

    -- USUARIO
    PROCEDURE OBTENER_USUARIO_POR_CREDENCIALES(p_nombre VARCHAR2, p_hash VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD,
        ACTIVO, FECHA_CREACION FROM USUARIO WHERE NOMBRE_USUARIO = p_nombre AND HASH_CONTRASENA = p_hash AND ACTIVO = 1; END;

    PROCEDURE OBTENER_USUARIO_POR_ID(p_id NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD,
        ACTIVO, FECHA_CREACION FROM USUARIO WHERE ID = p_id; END;

    PROCEDURE OBTENER_USUARIO_POR_DOCUMENTO(p_doc VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD,
        ACTIVO, FECHA_CREACION FROM USUARIO WHERE DOCUMENTO_IDENTIDAD = p_doc; END;

    PROCEDURE OBTENER_TODOS_USUARIOS(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD,
        ACTIVO, FECHA_CREACION FROM USUARIO WHERE ACTIVO = 1 ORDER BY NOMBRE_COMPLETO; END;

    PROCEDURE INSERTAR_USUARIO(p_user VARCHAR2, p_hash VARCHAR2, p_nombre VARCHAR2, p_rol NUMBER, p_doc VARCHAR2) IS
    BEGIN INSERT INTO USUARIO (NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD)
        VALUES (p_user, p_hash, p_nombre, p_rol, p_doc); COMMIT; END;

    PROCEDURE ACTUALIZAR_USUARIO(p_id NUMBER, p_nombre VARCHAR2, p_rol NUMBER, p_activo NUMBER) IS
    BEGIN UPDATE USUARIO SET NOMBRE_COMPLETO = p_nombre, ROL = p_rol, ACTIVO = p_activo WHERE ID = p_id; COMMIT; END;

    -- CLIENTE
    PROCEDURE OBTENER_CLIENTE_POR_DOCUMENTO(p_doc VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, DOCUMENTO, NOMBRE_COMPLETO, TELEFONO, CORREO, CHAT_ID, MEDICAMENTO_RECURRENTE,
        ACTIVO, FECHA_CREACION FROM CLIENTE WHERE DOCUMENTO = p_doc AND ACTIVO = 1; END;

    PROCEDURE OBTENER_CLIENTE_POR_ID(p_id NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, DOCUMENTO, NOMBRE_COMPLETO, TELEFONO, CORREO, CHAT_ID, MEDICAMENTO_RECURRENTE,
        ACTIVO, FECHA_CREACION FROM CLIENTE WHERE ID = p_id; END;

    PROCEDURE OBTENER_CLIENTE_POR_CHAT_ID(p_chat VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, DOCUMENTO, NOMBRE_COMPLETO, TELEFONO, CORREO, CHAT_ID, MEDICAMENTO_RECURRENTE,
        ACTIVO, FECHA_CREACION FROM CLIENTE WHERE CHAT_ID = p_chat AND ACTIVO = 1; END;

    PROCEDURE OBTENER_CLIENTES_FIDELIZACION(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, DOCUMENTO, NOMBRE_COMPLETO, TELEFONO, CORREO, CHAT_ID, MEDICAMENTO_RECURRENTE,
        ACTIVO, FECHA_CREACION FROM CLIENTE WHERE ACTIVO = 1 AND CHAT_ID IS NOT NULL ORDER BY NOMBRE_COMPLETO; END;

    PROCEDURE INSERTAR_CLIENTE(p_doc VARCHAR2, p_nombre VARCHAR2, p_tel VARCHAR2,
        p_correo VARCHAR2, p_chat VARCHAR2, p_med VARCHAR2) IS
    BEGIN INSERT INTO CLIENTE (DOCUMENTO, NOMBRE_COMPLETO, TELEFONO, CORREO, CHAT_ID, MEDICAMENTO_RECURRENTE)
        VALUES (p_doc, p_nombre, p_tel, p_correo, p_chat, p_med); COMMIT; END;

    PROCEDURE ACTUALIZAR_CLIENTE(p_id NUMBER, p_nombre VARCHAR2, p_tel VARCHAR2,
        p_correo VARCHAR2, p_chat VARCHAR2, p_med VARCHAR2) IS
    BEGIN UPDATE CLIENTE SET NOMBRE_COMPLETO = p_nombre, TELEFONO = p_tel, CORREO = p_correo,
        CHAT_ID = p_chat, MEDICAMENTO_RECURRENTE = p_med WHERE ID = p_id; COMMIT; END;

    -- PARAMETRO
    PROCEDURE OBTENER_TODOS_PARAMETROS(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT ID, CLAVE, VALOR, DESCRIPCION, ACTIVO, FECHA_CREACION
        FROM PARAMETRO_SISTEMA WHERE ACTIVO = 1 ORDER BY CLAVE; END;

    PROCEDURE INSERTAR_PARAMETRO(p_clave VARCHAR2, p_valor VARCHAR2, p_desc VARCHAR2) IS
    BEGIN INSERT INTO PARAMETRO_SISTEMA (CLAVE, VALOR, DESCRIPCION) VALUES (p_clave, p_valor, p_desc); COMMIT; END;

END PKG_PHARMASMART_CONFIG;
/

COMMIT;
SELECT 'Package CONFIG COMPLETO creado' AS MENSAJE FROM DUAL;
EXIT;