-- ============================================
-- PharmaSmart - Script 08 (CORREGIDO)
-- Package PKG_PHARMASMART_CONFIG
-- Ejecutar como PHARMA_USER
-- ============================================

SET SERVEROUTPUT ON;
SET ECHO ON;

CREATE OR REPLACE PACKAGE PKG_PHARMASMART_CONFIG AS
    
    FUNCTION OBTENER_PARAMETRO(p_clave VARCHAR2) RETURN VARCHAR2;
    PROCEDURE ACTUALIZAR_DESCUENTO_GENERAL(p_nuevo_valor VARCHAR2, p_id_usuario NUMBER, p_motivo VARCHAR2, p_ip VARCHAR2 DEFAULT NULL);
    PROCEDURE ACTUALIZAR_DESCUENTO_PRODUCTO(p_id_producto NUMBER, p_descuento NUMBER, p_id_usuario NUMBER, p_motivo VARCHAR2, p_ip VARCHAR2 DEFAULT NULL);
    PROCEDURE REGISTRAR_AJUSTE(p_id_lote NUMBER, p_tipo CHAR, p_cantidad NUMBER, p_motivo VARCHAR2, p_id_responsable NUMBER);
    
    PROCEDURE OBTENER_HISTORIAL_PARAMETROS(p_clave VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_HISTORIAL_POR_USUARIO(p_id_usuario NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_HISTORIAL_POR_FECHAS(p_desde DATE, p_hasta DATE, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_HISTORIAL_DESCUENTOS(p_id_producto NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_TODO_HISTORIAL_DESCUENTO(p_cursor OUT SYS_REFCURSOR);
    
    -- PRODUCTOS
    PROCEDURE OBTENER_PRODUCTO_POR_CODIGO(p_codigo VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_PRODUCTO_POR_ID(p_id_producto NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_PRODUCTO_POR_NOMBRE(p_nombre VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_TODOS_PRODUCTOS(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE INSERTAR_PRODUCTO(p_codigo VARCHAR2, p_nombre VARCHAR2, p_descripcion VARCHAR2, p_es_controlado CHAR, p_stock_minimo NUMBER, p_descuento NUMBER);
    PROCEDURE ACTUALIZAR_PRODUCTO(p_id_producto NUMBER, p_nombre VARCHAR2, p_descripcion VARCHAR2, p_es_controlado CHAR, p_stock_minimo NUMBER, p_descuento NUMBER);
    PROCEDURE ELIMINAR_PRODUCTO(p_id_producto NUMBER);
    
    -- USUARIOS
    PROCEDURE OBTENER_USUARIO_POR_CREDENCIALES(p_nombre VARCHAR2, p_hash VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_USUARIO_POR_ID(p_id_usuario NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_USUARIO_POR_DOCUMENTO(p_doc VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_TODOS_USUARIOS(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE INSERTAR_USUARIO(p_user VARCHAR2, p_hash VARCHAR2, p_nombre VARCHAR2, p_rol CHAR, p_doc VARCHAR2);
    PROCEDURE ACTUALIZAR_USUARIO(p_id_usuario NUMBER, p_nombre VARCHAR2, p_rol CHAR, p_estado CHAR);
    
    -- CLIENTES
    PROCEDURE OBTENER_CLIENTE_POR_DOCUMENTO(p_doc VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_CLIENTE_POR_ID(p_id_cliente NUMBER, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_CLIENTE_POR_CHAT_ID(p_chat VARCHAR2, p_cursor OUT SYS_REFCURSOR);
    PROCEDURE OBTENER_CLIENTES_FIDELIZACION(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE INSERTAR_CLIENTE(p_doc VARCHAR2, p_nombre VARCHAR2, p_tel VARCHAR2, p_correo VARCHAR2, p_chat VARCHAR2, p_med VARCHAR2);
    PROCEDURE ACTUALIZAR_CLIENTE(p_id_cliente NUMBER, p_nombre VARCHAR2, p_tel VARCHAR2, p_correo VARCHAR2, p_chat VARCHAR2, p_med VARCHAR2);
    
    -- PARAMETROS
    PROCEDURE OBTENER_TODOS_PARAMETROS(p_cursor OUT SYS_REFCURSOR);
    PROCEDURE INSERTAR_PARAMETRO(p_clave VARCHAR2, p_valor VARCHAR2, p_desc VARCHAR2);
    
END PKG_PHARMASMART_CONFIG;
/

CREATE OR REPLACE PACKAGE BODY PKG_PHARMASMART_CONFIG AS

    FUNCTION OBTENER_PARAMETRO(p_clave VARCHAR2) RETURN VARCHAR2 IS
        v_valor VARCHAR2(30);
    BEGIN SELECT VALOR INTO v_valor FROM PARAMETROS_SISTEMA WHERE CLAVE = p_clave; RETURN v_valor;
    EXCEPTION WHEN NO_DATA_FOUND THEN RETURN NULL; END;

    PROCEDURE ACTUALIZAR_DESCUENTO_GENERAL(p_nuevo_valor VARCHAR2, p_id_usuario NUMBER, p_motivo VARCHAR2, p_ip VARCHAR2 DEFAULT NULL) IS
        v_rol CHAR(1); v_anterior VARCHAR2(30);
    BEGIN
        SELECT ROL INTO v_rol FROM USUARIOS WHERE ID_USUARIO = p_id_usuario;
        IF v_rol != '1' THEN RAISE_APPLICATION_ERROR(-20004, 'Solo admin.'); END IF;
        SELECT VALOR INTO v_anterior FROM PARAMETROS_SISTEMA WHERE CLAVE = 'PORCENTAJE_DESCUENTO_VENCIMIENTO';
        UPDATE PARAMETROS_SISTEMA SET VALOR = p_nuevo_valor WHERE CLAVE = 'PORCENTAJE_DESCUENTO_VENCIMIENTO';
        INSERT INTO HISTORIAL_PARAMETROS (CLAVE_PARAMETRO, VALOR_ANTERIOR, VALOR_NUEVO, MOTIVO, ID_USUARIO, DIRECCION_IP)
        VALUES ('PORCENTAJE_DESCUENTO_VENCIMIENTO', v_anterior, p_nuevo_valor, p_motivo, p_id_usuario, p_ip);
        COMMIT;
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE; END;

    PROCEDURE ACTUALIZAR_DESCUENTO_PRODUCTO(p_id_producto NUMBER, p_descuento NUMBER, p_id_usuario NUMBER, p_motivo VARCHAR2, p_ip VARCHAR2 DEFAULT NULL) IS
        v_rol CHAR(1); v_prod PRODUCTOS%ROWTYPE; v_accion CHAR(1);
    BEGIN
        SELECT ROL INTO v_rol FROM USUARIOS WHERE ID_USUARIO = p_id_usuario;
        IF v_rol != '1' THEN RAISE_APPLICATION_ERROR(-20004, 'Solo admin.'); END IF;
        SELECT * INTO v_prod FROM PRODUCTOS WHERE ID_PRODUCTO = p_id_producto;
        IF v_prod.DESCUENTO_PROXIMIDAD_VENCIMIENTO IS NULL AND p_descuento IS NOT NULL THEN v_accion := 'C';
        ELSIF v_prod.DESCUENTO_PROXIMIDAD_VENCIMIENTO IS NOT NULL AND p_descuento IS NULL THEN v_accion := 'E';
        ELSE v_accion := 'M'; END IF;
        INSERT INTO HISTORIAL_DESCUENTOS (ID_PRODUCTO, CODIGO_PRODUCTO, NOMBRE_PRODUCTO, DESCUENTO_ANTERIOR, DESCUENTO_NUEVO, ACCION, MOTIVO, ID_USUARIO, DIRECCION_IP)
        VALUES (p_id_producto, v_prod.CODIGO, v_prod.NOMBRE, v_prod.DESCUENTO_PROXIMIDAD_VENCIMIENTO, p_descuento, v_accion, p_motivo, p_id_usuario, p_ip);
        UPDATE PRODUCTOS SET DESCUENTO_PROXIMIDAD_VENCIMIENTO = p_descuento WHERE ID_PRODUCTO = p_id_producto;
        COMMIT;
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE; END;

    PROCEDURE REGISTRAR_AJUSTE(p_id_lote NUMBER, p_tipo CHAR, p_cantidad NUMBER, p_motivo VARCHAR2, p_id_responsable NUMBER) IS
        v_estado CHAR(1); v_cant NUMBER;
    BEGIN
        INSERT INTO AJUSTES_INVENTARIO (ID_LOTE, TIPO, CANTIDAD, MOTIVO, ID_RESPONSABLE)
        VALUES (p_id_lote, p_tipo, p_cantidad, p_motivo, p_id_responsable);
        SELECT CANTIDAD_ACTUAL + p_cantidad INTO v_cant FROM LOTES WHERE ID_LOTE = p_id_lote;
        IF v_cant <= 0 THEN v_estado := 'V';
        ELSIF p_tipo = 'V' THEN v_estado := 'V';
        ELSIF p_tipo = 'R' THEN v_estado := 'C';
        ELSE SELECT ESTADO INTO v_estado FROM LOTES WHERE ID_LOTE = p_id_lote; END IF;
        UPDATE LOTES SET CANTIDAD_ACTUAL = v_cant, ESTADO = v_estado WHERE ID_LOTE = p_id_lote;
        COMMIT;
    EXCEPTION WHEN OTHERS THEN ROLLBACK; RAISE; END;

    PROCEDURE OBTENER_HISTORIAL_PARAMETROS(p_clave VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM HISTORIAL_PARAMETROS WHERE CLAVE_PARAMETRO = p_clave ORDER BY FECHA_CAMBIO DESC; END;

    PROCEDURE OBTENER_HISTORIAL_POR_USUARIO(p_id_usuario NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM HISTORIAL_PARAMETROS WHERE ID_USUARIO = p_id_usuario ORDER BY FECHA_CAMBIO DESC; END;

    PROCEDURE OBTENER_HISTORIAL_POR_FECHAS(p_desde DATE, p_hasta DATE, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM HISTORIAL_PARAMETROS WHERE FECHA_CAMBIO BETWEEN p_desde AND p_hasta ORDER BY FECHA_CAMBIO DESC; END;

    PROCEDURE OBTENER_HISTORIAL_DESCUENTOS(p_id_producto NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM HISTORIAL_DESCUENTOS WHERE ID_PRODUCTO = p_id_producto ORDER BY FECHA_CAMBIO DESC; END;

    PROCEDURE OBTENER_TODO_HISTORIAL_DESCUENTO(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM HISTORIAL_DESCUENTOS ORDER BY FECHA_CAMBIO DESC; END;

    -- PRODUCTOS
    PROCEDURE OBTENER_PRODUCTO_POR_CODIGO(p_codigo VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM PRODUCTOS WHERE CODIGO = p_codigo AND ESTADO = 'A'; END;

    PROCEDURE OBTENER_PRODUCTO_POR_ID(p_id_producto NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM PRODUCTOS WHERE ID_PRODUCTO = p_id_producto; END;

    PROCEDURE OBTENER_PRODUCTO_POR_NOMBRE(p_nombre VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM PRODUCTOS WHERE UPPER(NOMBRE) = UPPER(p_nombre) AND ESTADO = 'A'; END;

    PROCEDURE OBTENER_TODOS_PRODUCTOS(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM PRODUCTOS WHERE ESTADO = 'A' ORDER BY NOMBRE; END;

    PROCEDURE INSERTAR_PRODUCTO(p_codigo VARCHAR2, p_nombre VARCHAR2, p_descripcion VARCHAR2, p_es_controlado CHAR, p_stock_minimo NUMBER, p_descuento NUMBER) IS
    BEGIN INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO, DESCUENTO_PROXIMIDAD_VENCIMIENTO)
        VALUES (p_codigo, p_nombre, p_descripcion, p_es_controlado, p_stock_minimo, p_descuento); COMMIT; END;

    PROCEDURE ACTUALIZAR_PRODUCTO(p_id_producto NUMBER, p_nombre VARCHAR2, p_descripcion VARCHAR2, p_es_controlado CHAR, p_stock_minimo NUMBER, p_descuento NUMBER) IS
    BEGIN UPDATE PRODUCTOS SET NOMBRE = p_nombre, DESCRIPCION = p_descripcion, ES_CONTROLADO = p_es_controlado,
        STOCK_MINIMO = p_stock_minimo, DESCUENTO_PROXIMIDAD_VENCIMIENTO = p_descuento WHERE ID_PRODUCTO = p_id_producto; COMMIT; END;

    PROCEDURE ELIMINAR_PRODUCTO(p_id_producto NUMBER) IS
    BEGIN UPDATE PRODUCTOS SET ESTADO = 'I' WHERE ID_PRODUCTO = p_id_producto; COMMIT; END;

    -- USUARIOS
    PROCEDURE OBTENER_USUARIO_POR_CREDENCIALES(p_nombre VARCHAR2, p_hash VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM USUARIOS WHERE NOMBRE_USUARIO = p_nombre AND HASH_CONTRASENA = p_hash AND ESTADO = 'A'; END;

    PROCEDURE OBTENER_USUARIO_POR_ID(p_id_usuario NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM USUARIOS WHERE ID_USUARIO = p_id_usuario; END;

    PROCEDURE OBTENER_USUARIO_POR_DOCUMENTO(p_doc VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM USUARIOS WHERE DOCUMENTO_IDENTIDAD = p_doc; END;

    PROCEDURE OBTENER_TODOS_USUARIOS(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM USUARIOS WHERE ESTADO = 'A' ORDER BY NOMBRE_COMPLETO; END;

    PROCEDURE INSERTAR_USUARIO(p_user VARCHAR2, p_hash VARCHAR2, p_nombre VARCHAR2, p_rol CHAR, p_doc VARCHAR2) IS
    BEGIN INSERT INTO USUARIOS (NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD)
        VALUES (p_user, p_hash, p_nombre, p_rol, p_doc); COMMIT; END;

    PROCEDURE ACTUALIZAR_USUARIO(p_id_usuario NUMBER, p_nombre VARCHAR2, p_rol CHAR, p_estado CHAR) IS
    BEGIN UPDATE USUARIOS SET NOMBRE_COMPLETO = p_nombre, ROL = p_rol, ESTADO = p_estado WHERE ID_USUARIO = p_id_usuario; COMMIT; END;

    -- CLIENTES
    PROCEDURE OBTENER_CLIENTE_POR_DOCUMENTO(p_doc VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM CLIENTES WHERE DOCUMENTO = p_doc AND ESTADO = 'A'; END;

    PROCEDURE OBTENER_CLIENTE_POR_ID(p_id_cliente NUMBER, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM CLIENTES WHERE ID_CLIENTE = p_id_cliente; END;

    PROCEDURE OBTENER_CLIENTE_POR_CHAT_ID(p_chat VARCHAR2, p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM CLIENTES WHERE CHAT_ID = p_chat AND ESTADO = 'A'; END;

    PROCEDURE OBTENER_CLIENTES_FIDELIZACION(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM CLIENTES WHERE ESTADO = 'A' AND CHAT_ID IS NOT NULL ORDER BY NOMBRE_COMPLETO; END;

    PROCEDURE INSERTAR_CLIENTE(p_doc VARCHAR2, p_nombre VARCHAR2, p_tel VARCHAR2, p_correo VARCHAR2, p_chat VARCHAR2, p_med VARCHAR2) IS
    BEGIN INSERT INTO CLIENTES (DOCUMENTO, NOMBRE_COMPLETO, TELEFONO, CORREO, CHAT_ID, MEDICAMENTO_RECURRENTE)
        VALUES (p_doc, p_nombre, p_tel, p_correo, p_chat, p_med); COMMIT; END;

    PROCEDURE ACTUALIZAR_CLIENTE(p_id_cliente NUMBER, p_nombre VARCHAR2, p_tel VARCHAR2, p_correo VARCHAR2, p_chat VARCHAR2, p_med VARCHAR2) IS
    BEGIN UPDATE CLIENTES SET NOMBRE_COMPLETO = p_nombre, TELEFONO = p_tel, CORREO = p_correo,
        CHAT_ID = p_chat, MEDICAMENTO_RECURRENTE = p_med WHERE ID_CLIENTE = p_id_cliente; COMMIT; END;

    -- PARAMETROS
    PROCEDURE OBTENER_TODOS_PARAMETROS(p_cursor OUT SYS_REFCURSOR) IS
    BEGIN OPEN p_cursor FOR SELECT * FROM PARAMETROS_SISTEMA ORDER BY CLAVE; END;

    PROCEDURE INSERTAR_PARAMETRO(p_clave VARCHAR2, p_valor VARCHAR2, p_desc VARCHAR2) IS
    BEGIN INSERT INTO PARAMETROS_SISTEMA (CLAVE, VALOR, DESCRIPCION) VALUES (p_clave, p_valor, p_desc); COMMIT; END;

END PKG_PHARMASMART_CONFIG;
/

COMMIT;
PROMPT Package CONFIG creado.
EXIT;