-- ============================================
-- PharmaSmart - Script 12 (CORREGIDO)
-- Inserción de Datos Iniciales
-- Ejecutar como PHARMA_USER
-- ============================================

SET SERVEROUTPUT ON;
SET ECHO ON;

PROMPT Insertando datos iniciales...

-- USUARIOS (contraseña: "123456")
INSERT INTO USUARIOS (NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD)
VALUES ('admin', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Luis Ariza', '1', '1234567890');

INSERT INTO USUARIOS (NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD)
VALUES ('cajero1', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Sebastian Ramos', '2', '0987654321');

INSERT INTO USUARIOS (NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD)
VALUES ('farmaceutico', '8d969eef6ecad3c29a3a629280e686cf0c3f5d5a86aff3ca12020c923adc6c92', 'Juan Miguel Debillero', '3', '1122334455');

-- PRODUCTOS
INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO)
VALUES ('IBU-001', 'Ibuprofeno 400mg', 'Antiinflamatorio, caja x 20', 'N', 10);

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO)
VALUES ('LOR-005', 'Loratadina 10mg', 'Antihistaminico, caja x 10', 'N', 5);

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO)
VALUES ('TRAM-02', 'Tramadol 50mg', 'Analgesico opioide, caja x 10', 'S', 3);

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO)
VALUES ('INSU-05', 'Insulina Glargina 100UI', 'Insulina de accion prolongada, vial 10ml', 'S', 2);

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO, DESCUENTO_PROXIMIDAD_VENCIMIENTO)
VALUES ('LOS-10', 'Losartan 50mg', 'Antihipertensivo, caja x 30', 'N', 8, 0.15);

-- LOTES
INSERT INTO LOTES (CODIGO_LOTE, ID_PRODUCTO, FECHA_FABRICACION, FECHA_VENCIMIENTO, PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL)
VALUES ('L-IBU-01', 1, TO_DATE('01/01/2025','DD/MM/YYYY'), SYSDATE + 15, 5000, 12000, 20, 100);

INSERT INTO LOTES (CODIGO_LOTE, ID_PRODUCTO, FECHA_FABRICACION, FECHA_VENCIMIENTO, PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL)
VALUES ('L-IBU-02', 1, TO_DATE('01/03/2026','DD/MM/YYYY'), TO_DATE('01/03/2028','DD/MM/YYYY'), 5500, 12000, 80, 100);

INSERT INTO LOTES (CODIGO_LOTE, ID_PRODUCTO, FECHA_FABRICACION, FECHA_VENCIMIENTO, PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL)
VALUES ('L-IBU-03', 1, TO_DATE('01/06/2024','DD/MM/YYYY'), TO_DATE('01/06/2026','DD/MM/YYYY'), 4500, 11000, 5, 50);

INSERT INTO LOTES (CODIGO_LOTE, ID_PRODUCTO, FECHA_FABRICACION, FECHA_VENCIMIENTO, PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL)
VALUES ('L-LOR-01', 2, TO_DATE('01/02/2026','DD/MM/YYYY'), TO_DATE('01/02/2028','DD/MM/YYYY'), 8000, 18000, 30, 50);

INSERT INTO LOTES (CODIGO_LOTE, ID_PRODUCTO, FECHA_FABRICACION, FECHA_VENCIMIENTO, PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL)
VALUES ('L-TRA-01', 3, TO_DATE('01/01/2026','DD/MM/YYYY'), TO_DATE('01/01/2028','DD/MM/YYYY'), 75000, 85000, 10, 20);

INSERT INTO LOTES (CODIGO_LOTE, ID_PRODUCTO, FECHA_FABRICACION, FECHA_VENCIMIENTO, PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL)
VALUES ('L-INS-01', 4, TO_DATE('01/03/2026','DD/MM/YYYY'), TO_DATE('01/09/2026','DD/MM/YYYY'), 140000, 150000, 5, 10);

INSERT INTO LOTES (CODIGO_LOTE, ID_PRODUCTO, FECHA_FABRICACION, FECHA_VENCIMIENTO, PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL)
VALUES ('L-LOS-01', 5, TO_DATE('01/04/2026','DD/MM/YYYY'), TO_DATE('01/04/2028','DD/MM/YYYY'), 8500, 15000, 40, 50);

INSERT INTO LOTES (CODIGO_LOTE, ID_PRODUCTO, FECHA_FABRICACION, FECHA_VENCIMIENTO, PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL)
VALUES ('L-LOS-02', 5, TO_DATE('01/01/2026','DD/MM/YYYY'), SYSDATE + 20, 8000, 14000, 10, 30);

-- CLIENTES
INSERT INTO CLIENTES (DOCUMENTO, NOMBRE_COMPLETO, TELEFONO, CORREO, MEDICAMENTO_RECURRENTE)
VALUES ('1234567890', 'Maria Perez', '3001234567', 'maria@email.com', 'Ibuprofeno 400mg');

INSERT INTO CLIENTES (DOCUMENTO, NOMBRE_COMPLETO, TELEFONO, CORREO, MEDICAMENTO_RECURRENTE)
VALUES ('0987654321', 'Carlos Gomez', '3109876543', 'carlos@email.com', 'Losartan 50mg');

-- PARAMETROS
INSERT INTO PARAMETROS_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('PORCENTAJE_DESCUENTO_VENCIMIENTO', '0.20', 'Descuento en ventana critica (30 dias)');

INSERT INTO PARAMETROS_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('UMBRAL_ALERTA_INFLACION', '5.00', 'Porcentaje minimo para alerta');

INSERT INTO PARAMETROS_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('DIAS_VENTANA_CRITICA', '30', 'Dias antes del vencimiento');

INSERT INTO PARAMETROS_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('TELEGRAM_BOT_TOKEN', 'TU_TOKEN_AQUI', 'Token del Bot de Telegram');

INSERT INTO PARAMETROS_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('TELEGRAM_HABILITADO', '0', 'Habilitar (1) o deshabilitar (0)');

INSERT INTO PARAMETROS_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('DIAS_ANTICIPACION_REPOSICION', '5', 'Dias de anticipacion para notificar');

COMMIT;

PROMPT Datos insertados correctamente.

SELECT COUNT(*) AS USUARIOS FROM USUARIOS;
SELECT COUNT(*) AS PRODUCTOS FROM PRODUCTOS;
SELECT COUNT(*) AS LOTES FROM LOTES;
SELECT COUNT(*) AS CLIENTES FROM CLIENTES;
SELECT COUNT(*) AS PARAMETROS FROM PARAMETROS_SISTEMA;

COMMIT;

-- ============================================
-- ACTIVAR TRIGGERS DESPUÉS DE LA CARGA INICIAL
-- ============================================
PROMPT ========================================
PROMPT Activando triggers para operación normal...
PROMPT ========================================

ALTER TRIGGER TRG_ALERTA_INFLACION ENABLE;

PROMPT TRG_ALERTA_INFLACION: AHORA HABILITADO

-- Verificar estado final
SELECT 
    TRIGGER_NAME, 
    STATUS 
FROM USER_TRIGGERS 
ORDER BY TRIGGER_NAME;

PROMPT ========================================
PROMPT Datos insertados y triggers activados.
PROMPT ========================================

EXIT;