-- ============================================
-- PharmaSmart - Script 12
-- Inserción de Datos Iniciales
-- Ejecutar como PHARMA_USER
-- ============================================

SET SERVEROUTPUT ON;
SET ECHO ON;

-- Usuarios (contraseña: "123456")
INSERT INTO USUARIO (NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD)
VALUES ('admin', 'e10adc3949ba59abbe56e057f20f883e', 'Luis Ariza', 1, '1234567890');

INSERT INTO USUARIO (NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD)
VALUES ('cajero1', 'e10adc3949ba59abbe56e057f20f883e', 'Sebastian Ramos', 2, '0987654321');

INSERT INTO USUARIO (NOMBRE_USUARIO, HASH_CONTRASENA, NOMBRE_COMPLETO, ROL, DOCUMENTO_IDENTIDAD)
VALUES ('farmaceutico', 'e10adc3949ba59abbe56e057f20f883e', 'Juan Miguel Debillero', 3, '1122334455');

-- Productos
INSERT INTO PRODUCTO (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO)
VALUES ('IBU-001', 'Ibuprofeno 400mg', 'Antiinflamatorio no esteroideo, caja x 20 tabletas', 0, 10);

INSERT INTO PRODUCTO (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO)
VALUES ('LOR-005', 'Loratadina 10mg', 'Antihistaminico, caja x 10 tabletas', 0, 5);

INSERT INTO PRODUCTO (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO)
VALUES ('TRAM-02', 'Tramadol 50mg', 'Analgesico opioide, caja x 10 tabletas', 1, 3);

INSERT INTO PRODUCTO (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO)
VALUES ('INSU-05', 'Insulina Glargina 100UI', 'Insulina de accion prolongada, vial 10ml', 1, 2);

INSERT INTO PRODUCTO (CODIGO, NOMBRE, DESCRIPCION, ES_CONTROLADO, STOCK_MINIMO, DESCUENTO_PROXIMIDAD_VENCIMIENTO)
VALUES ('LOS-10', 'Losartan 50mg', 'Antihipertensivo, caja x 30 tabletas', 0, 8, 0.15);

-- Lotes
INSERT INTO LOTE (CODIGO_LOTE, PRODUCTO_ID, FECHA_FABRICACION, FECHA_VENCIMIENTO, 
                  PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL, ESTADO)
VALUES ('L-IBU-01', 1, '01/01/2025', SYSDATE + 15, 5000, 12000, 20, 100, 1);

INSERT INTO LOTE (CODIGO_LOTE, PRODUCTO_ID, FECHA_FABRICACION, FECHA_VENCIMIENTO, 
                  PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL, ESTADO)
VALUES ('L-IBU-02', 1, '01/03/2026', '01/03/2028', 5500, 12000, 80, 100, 1);

INSERT INTO LOTE (CODIGO_LOTE, PRODUCTO_ID, FECHA_FABRICACION, FECHA_VENCIMIENTO, 
                  PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL, ESTADO)
VALUES ('L-IBU-03', 1, '01/06/2024', '01/06/2026', 4500, 11000, 5, 50, 1);

INSERT INTO LOTE (CODIGO_LOTE, PRODUCTO_ID, FECHA_FABRICACION, FECHA_VENCIMIENTO, 
                  PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL, ESTADO)
VALUES ('L-LOR-01', 2, '01/02/2026', '01/02/2028', 8000, 18000, 30, 50, 1);

INSERT INTO LOTE (CODIGO_LOTE, PRODUCTO_ID, FECHA_FABRICACION, FECHA_VENCIMIENTO, 
                  PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL, ESTADO)
VALUES ('L-TRA-01', 3, '01/01/2026', '01/01/2028', 75000, 85000, 10, 20, 1);

INSERT INTO LOTE (CODIGO_LOTE, PRODUCTO_ID, FECHA_FABRICACION, FECHA_VENCIMIENTO, 
                  PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL, ESTADO)
VALUES ('L-INS-01', 4, '01/03/2026', '01/09/2026', 140000, 150000, 5, 10, 1);

INSERT INTO LOTE (CODIGO_LOTE, PRODUCTO_ID, FECHA_FABRICACION, FECHA_VENCIMIENTO, 
                  PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL, ESTADO)
VALUES ('L-LOS-01', 5, '01/04/2026', '01/04/2028', 8500, 15000, 40, 50, 1);

INSERT INTO LOTE (CODIGO_LOTE, PRODUCTO_ID, FECHA_FABRICACION, FECHA_VENCIMIENTO, 
                  PRECIO_COMPRA, PRECIO_VENTA, CANTIDAD_ACTUAL, CANTIDAD_INICIAL, ESTADO)
VALUES ('L-LOS-02', 5, '01/01/2026', SYSDATE + 20, 8000, 14000, 10, 30, 1);

-- Clientes
INSERT INTO CLIENTE (DOCUMENTO, NOMBRE_COMPLETO, TELEFONO, CORREO, MEDICAMENTO_RECURRENTE)
VALUES ('1234567890', 'Maria Perez', '3001234567', 'maria@email.com', 'Ibuprofeno 400mg');

INSERT INTO CLIENTE (DOCUMENTO, NOMBRE_COMPLETO, TELEFONO, CORREO, MEDICAMENTO_RECURRENTE)
VALUES ('0987654321', 'Carlos Gomez', '3109876543', 'carlos@email.com', 'Losartan 50mg');

-- Parámetros
INSERT INTO PARAMETRO_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('PORCENTAJE_DESCUENTO_VENCIMIENTO', '0.20', 'Descuento en ventana critica (30 dias)');

INSERT INTO PARAMETRO_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('UMBRAL_ALERTA_INFLACION', '5.00', 'Porcentaje minimo para alerta de inflacion');

INSERT INTO PARAMETRO_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('DIAS_VENTANA_CRITICA', '30', 'Dias antes del vencimiento para descuento');

INSERT INTO PARAMETRO_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('TELEGRAM_BOT_TOKEN', 'TU_TOKEN_AQUI', 'Token del Bot de Telegram');

INSERT INTO PARAMETRO_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('TELEGRAM_HABILITADO', '0', 'Habilitar (1) o deshabilitar (0) el Bot');

INSERT INTO PARAMETRO_SISTEMA (CLAVE, VALOR, DESCRIPCION)
VALUES ('DIAS_ANTICIPACION_REPOSICION', '5', 'Dias de anticipacion para notificar');

COMMIT;

SELECT 'Datos insertados correctamente' AS MENSAJE FROM DUAL;
SELECT 'Usuarios: ' || COUNT(*) FROM USUARIO;
SELECT 'Productos: ' || COUNT(*) FROM PRODUCTO;
SELECT 'Lotes: ' || COUNT(*) FROM LOTE;
SELECT 'Clientes: ' || COUNT(*) FROM CLIENTE;
SELECT 'Parametros: ' || COUNT(*) FROM PARAMETRO_SISTEMA;

EXIT;